### ISSUE TITLE
Create a merchant system?

### ISSUE THREAD

**Issue by f1nn3g4n** [f1nn3g4n/npc#8]
With my async campaign, it could be cool to create a merchant type for characters and give them inventory that is purchaseable! 

Basically:
- allow characters to be toggled as a merchant
- allow assigning inventory
- / command for seeing merchants
- / command for purchasing from merchant
- / command for entering a roll and getting a discount
- / command to trade? I think that needs to be roleplayed by DM
- / command for transactions? Might be nice but idk necessary. Greater load for storage too.
    - maybe a new channel to log that? No storage on server-side
- inventory class: `{ name, cost, discountThres?, discount?, stock = 1, description }`

**Comment by Ninety1zeus** [comment]
Dude I just found your bot. The description alone is mind blowing. I think you have something big. I currently run an rp server for GTA I’ve just added your bot, and I’d love to keep contact for updates and just common communication. I think this is going to be my fav bot!

**Comment by f1nn3g4n** [comment]
@Ninety1zeus Happy to hear you are enjoying my bot!! 😁 I'm open to suggestions or fixes you want too! This is very much something I try to get to in my free time, so I may be slow haha.

I have a server for the bot here https://discord.gg/xjQGEwX5, feel free to join!
